server:
  port: 9001
  context-path: /whale
  #启用gzip压缩,并设置压缩支持的格式(默认支持text/html)
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain
    #默认仅压缩2048kb以上的内容
    min-response-size: 1024
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: false
    cache-enabled: false
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 0
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: false
    #刷新mapper
    refresh-mapper: true
    #逻辑删除配置（3个配置）
    logic-delete-value: 1
    logic-not-delete-value: 0
    sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
spring:
  devtools:
    restart:
      enabled: true
  http:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
  profiles:
    active: dev
  boot:
    admin:
      username: admin
      password: htwater
      client:
        prefer-ip: true
        name: contour test
        url: http://172.16.35.59:8082/monitor #监控服务器地址
debug: false
htweb:
  jwt:
    url: /login
    token:
      secret: 7a50fa6277dbed87588197d360637855
  cors:
    enabled: true
  swagger:
    global-operation-parameters:
      0:
        name: Authorization
        description: 认证
        modelRef: String
        parameterType: header

security:
  enable-csrf: false
management:
  security:
    enabled: false
  context-path: /monitor
